### ISSUE TITLE
project name

### ISSUE THREAD

**Issue by ozanj** [eddatasci/unrollment#10]
when I thought of the name "unrollment project" I was thinking of Michael Lewis's book "The Undoing Project" about the work of Kahneman and Tversky 
https://en.wikipedia.org/wiki/The_Undoing_Project 

right now the repo name is "unrollment" but I don't think this conveys the link to "the undoing project"; I liked Ben's idea of having repo name be "unrollment_proj" which does a better job of getting at the Kahneman/Tversky biography and also is a not to us building this project in R [i.e., .proj]

I should have made this comment before Ben closed the "are we doing this" issue. my bad

do folks agree w/ me that "unrollment_proj" is better name for repo than "unrollment"?

is it hard to change name of repo to unrollment_proj?

where in main page of github repo [or maybe in the associated website we eventually develop] can we write out the project title in full: "The Unrollment Project."

I'm sorry my issues lack brevity!

**Comment by btskinner** [comment]
It's easy to update the repo name. We may need to update the remotes on our personal machines, but that is easy. It's definitely easier now to change repo names than later when people are maybe looking for it.

I'm in favor of changing the repo name to `unrollment_proj` and the name (in the GitHub title and on the primary README file) to "The Unrollment Project".

**Comment by ozanj** [comment]
I like Ben's proposals!

**Comment by btskinner** [comment]
Okay, I'll change later today and let people know how to update their remotes if necessary.

**Comment by btskinner** [comment]
Ok everyone (@ozanj, @ksalazar3, @mpatricia01, @wdoyle42): I've renamed the repo to `unrollment_proj`. You can either:

1. Delete the old and reclone using the new name
2. Change your remote

If you are in the `unrollment_proj` directory on your computer, you can run this in the terminal to check the current remote:
```bash
[unrollment_proj] $ git remote -v
```
Most likely you will see:
```bash
origin	https://github.com/eddatasci/unrollment.git (fetch)
origin	https://github.com/eddatasci/unrollment.git (push)
```
Just do the following to change:
```bash
[unrollment_proj] $ git remote set-url origin https://github.com/eddatasci/unrollment_proj.git
```
If you check the remote again, you should see the new name:
```bash
[unrollment_proj] $ git remote -v
origin	https://github.com/eddatasci/unrollment_proj.git (fetch)
origin	https://github.com/eddatasci/unrollment_proj.git (push)
```
**NB** for @wdoyle42: since you are using TFA (and maybe a ssh key?), your remote is probably like mine:  `git@github.com:eddatasci/unrollment_proj.git`
